// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: config.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const clearSelectedDevice = `-- name: ClearSelectedDevice :exec
UPDATE ble_devices SET selected = 0 WHERE selected = 1
`

func (q *Queries) ClearSelectedDevice(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSelectedDevice)
	return err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM ble_devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSelectedDevice = `-- name: GetSelectedDevice :one
SELECT id, native_id, name, address, write_uuid, notify_uuid, selected, last_seen_at, updated_at FROM ble_devices WHERE selected = 1 LIMIT 1
`

func (q *Queries) GetSelectedDevice(ctx context.Context) (*BleDevice, error) {
	row := q.db.QueryRowContext(ctx, getSelectedDevice)
	var i BleDevice
	err := row.Scan(
		&i.ID,
		&i.NativeID,
		&i.Name,
		&i.Address,
		&i.WriteUuid,
		&i.NotifyUuid,
		&i.Selected,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, ipp_name, printer_uuid, ipp_listen, admin_listen, advertise, airprint, updated_at FROM app_settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (*AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.IppName,
		&i.PrinterUuid,
		&i.IppListen,
		&i.AdminListen,
		&i.Advertise,
		&i.Airprint,
		&i.UpdatedAt,
	)
	return &i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, native_id, name, address, write_uuid, notify_uuid, selected, last_seen_at, updated_at FROM ble_devices ORDER BY selected DESC, last_seen_at DESC, name ASC
`

func (q *Queries) ListDevices(ctx context.Context) ([]*BleDevice, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*BleDevice{}
	for rows.Next() {
		var i BleDevice
		if err := rows.Scan(
			&i.ID,
			&i.NativeID,
			&i.Name,
			&i.Address,
			&i.WriteUuid,
			&i.NotifyUuid,
			&i.Selected,
			&i.LastSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDevice = `-- name: SelectDevice :execrows
UPDATE ble_devices SET selected = 1, updated_at = ? WHERE id = ?
`

type SelectDeviceParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

func (q *Queries) SelectDevice(ctx context.Context, arg SelectDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, selectDevice, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPrinterUUID = `-- name: SetPrinterUUID :exec
UPDATE app_settings SET printer_uuid = ?, updated_at = ? WHERE id = 1
`

type SetPrinterUUIDParams struct {
	PrinterUuid string `json:"printer_uuid"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) SetPrinterUUID(ctx context.Context, arg SetPrinterUUIDParams) error {
	_, err := q.db.ExecContext(ctx, setPrinterUUID, arg.PrinterUuid, arg.UpdatedAt)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE app_settings
SET ipp_name = ?, ipp_listen = ?, admin_listen = ?, advertise = ?, airprint = ?, updated_at = ?
WHERE id = 1
RETURNING id, ipp_name, printer_uuid, ipp_listen, admin_listen, advertise, airprint, updated_at
`

type UpdateSettingsParams struct {
	IppName     string `json:"ipp_name"`
	IppListen   string `json:"ipp_listen"`
	AdminListen string `json:"admin_listen"`
	Advertise   int64  `json:"advertise"`
	Airprint    int64  `json:"airprint"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (*AppSetting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.IppName,
		arg.IppListen,
		arg.AdminListen,
		arg.Advertise,
		arg.Airprint,
		arg.UpdatedAt,
	)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.IppName,
		&i.PrinterUuid,
		&i.IppListen,
		&i.AdminListen,
		&i.Advertise,
		&i.Airprint,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO ble_devices (
    native_id, name, address, write_uuid, notify_uuid, selected, last_seen_at, updated_at
) VALUES (?, ?, ?, ?, ?, 0, ?, ?)
ON CONFLICT(native_id) DO UPDATE SET
    name = excluded.name,
    address = excluded.address,
    write_uuid = excluded.write_uuid,
    notify_uuid = excluded.notify_uuid,
    last_seen_at = excluded.last_seen_at,
    updated_at = excluded.updated_at
RETURNING id, native_id, name, address, write_uuid, notify_uuid, selected, last_seen_at, updated_at
`

type UpsertDeviceParams struct {
	NativeID   string         `json:"native_id"`
	Name       string         `json:"name"`
	Address    string         `json:"address"`
	WriteUuid  string         `json:"write_uuid"`
	NotifyUuid sql.NullString `json:"notify_uuid"`
	LastSeenAt int64          `json:"last_seen_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (*BleDevice, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice,
		arg.NativeID,
		arg.Name,
		arg.Address,
		arg.WriteUuid,
		arg.NotifyUuid,
		arg.LastSeenAt,
		arg.UpdatedAt,
	)
	var i BleDevice
	err := row.Scan(
		&i.ID,
		&i.NativeID,
		&i.Name,
		&i.Address,
		&i.WriteUuid,
		&i.NotifyUuid,
		&i.Selected,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return &i, err
}
