// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: config.sql

package sqlitedb

import (
	"context"
)

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = ? AND transport = 'usb'
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDevice = `-- name: GetDevice :one
SELECT id, native_id, name, address, write_uuid, notify_uuid, last_seen_at, updated_at, transport FROM devices WHERE id = ? AND transport = 'usb'
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (*Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.NativeID,
		&i.Name,
		&i.Address,
		&i.WriteUuid,
		&i.NotifyUuid,
		&i.LastSeenAt,
		&i.UpdatedAt,
		&i.Transport,
	)
	return &i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, native_id, name, address, write_uuid, notify_uuid, last_seen_at, updated_at, transport FROM devices WHERE transport = 'usb' ORDER BY last_seen_at DESC, name ASC
`

func (q *Queries) ListDevices(ctx context.Context) ([]*Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.NativeID,
			&i.Name,
			&i.Address,
			&i.WriteUuid,
			&i.NotifyUuid,
			&i.LastSeenAt,
			&i.UpdatedAt,
			&i.Transport,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (
    transport, native_id, name, address, write_uuid, notify_uuid, last_seen_at, updated_at
) VALUES ('usb', ?, ?, ?, '', NULL, ?, ?)
ON CONFLICT(native_id) DO UPDATE SET
    transport = 'usb',
    name = excluded.name,
    address = excluded.address,
    write_uuid = '',
    notify_uuid = NULL,
    last_seen_at = excluded.last_seen_at,
    updated_at = excluded.updated_at
RETURNING id, native_id, name, address, write_uuid, notify_uuid, last_seen_at, updated_at, transport
`

type UpsertDeviceParams struct {
	NativeID   string `json:"native_id"`
	Name       string `json:"name"`
	Address    string `json:"address"`
	LastSeenAt int64  `json:"last_seen_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (*Device, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice,
		arg.NativeID,
		arg.Name,
		arg.Address,
		arg.LastSeenAt,
		arg.UpdatedAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.NativeID,
		&i.Name,
		&i.Address,
		&i.WriteUuid,
		&i.NotifyUuid,
		&i.LastSeenAt,
		&i.UpdatedAt,
		&i.Transport,
	)
	return &i, err
}
