// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: jobs.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const abortInterruptedJobs = `-- name: AbortInterruptedJobs :exec
UPDATE print_jobs
SET state = 'aborted', completed_at = ?, error = 'service restarted while job state was uncertain'
WHERE state IN ('pending', 'processing')
`

func (q *Queries) AbortInterruptedJobs(ctx context.Context, completedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, abortInterruptedJobs, completedAt)
	return err
}

const abortJob = `-- name: AbortJob :execrows
UPDATE print_jobs SET state = 'aborted', completed_at = ?, error = ? WHERE id = ? AND state IN ('pending', 'processing')
`

type AbortJobParams struct {
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Error       sql.NullString `json:"error"`
	ID          int64          `json:"id"`
}

func (q *Queries) AbortJob(ctx context.Context, arg AbortJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, abortJob, arg.CompletedAt, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelJob = `-- name: CancelJob :execrows
UPDATE print_jobs SET state = 'canceled', completed_at = ? WHERE id = ? AND state IN ('pending', 'processing')
`

type CancelJobParams struct {
	CompletedAt sql.NullInt64 `json:"completed_at"`
	ID          int64         `json:"id"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelJob, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE print_jobs SET state = 'completed', completed_at = ?, error = NULL WHERE id = ? AND state = 'processing'
`

type CompleteJobParams struct {
	CompletedAt sql.NullInt64 `json:"completed_at"`
	ID          int64         `json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeJob, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createJob = `-- name: CreateJob :one
INSERT INTO print_jobs (
    printer_id, name, user_name, state, document_format, copies, bytes, error, created_at
) VALUES (?, ?, ?, 'pending', ?, ?, ?, NULL, ?)
RETURNING id, printer_id, name, user_name, state, document_format, copies, bytes, error, created_at, started_at, completed_at
`

type CreateJobParams struct {
	PrinterID      int64  `json:"printer_id"`
	Name           string `json:"name"`
	UserName       string `json:"user_name"`
	DocumentFormat string `json:"document_format"`
	Copies         int64  `json:"copies"`
	Bytes          int64  `json:"bytes"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (*PrintJob, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.PrinterID,
		arg.Name,
		arg.UserName,
		arg.DocumentFormat,
		arg.Copies,
		arg.Bytes,
		arg.CreatedAt,
	)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.PrinterID,
		&i.Name,
		&i.UserName,
		&i.State,
		&i.DocumentFormat,
		&i.Copies,
		&i.Bytes,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const getJob = `-- name: GetJob :one
SELECT id, printer_id, name, user_name, state, document_format, copies, bytes, error, created_at, started_at, completed_at FROM print_jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (*PrintJob, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i PrintJob
	err := row.Scan(
		&i.ID,
		&i.PrinterID,
		&i.Name,
		&i.UserName,
		&i.State,
		&i.DocumentFormat,
		&i.Copies,
		&i.Bytes,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, printer_id, name, user_name, state, document_format, copies, bytes, error, created_at, started_at, completed_at FROM print_jobs ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]*PrintJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PrintJob{}
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.PrinterID,
			&i.Name,
			&i.UserName,
			&i.State,
			&i.DocumentFormat,
			&i.Copies,
			&i.Bytes,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByPrinter = `-- name: ListJobsByPrinter :many
SELECT id, printer_id, name, user_name, state, document_format, copies, bytes, error, created_at, started_at, completed_at FROM print_jobs WHERE printer_id = ? ORDER BY id DESC LIMIT ?
`

type ListJobsByPrinterParams struct {
	PrinterID int64 `json:"printer_id"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) ListJobsByPrinter(ctx context.Context, arg ListJobsByPrinterParams) ([]*PrintJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByPrinter, arg.PrinterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PrintJob{}
	for rows.Next() {
		var i PrintJob
		if err := rows.Scan(
			&i.ID,
			&i.PrinterID,
			&i.Name,
			&i.UserName,
			&i.State,
			&i.DocumentFormat,
			&i.Copies,
			&i.Bytes,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneJobs = `-- name: PruneJobs :exec
DELETE FROM print_jobs
WHERE id NOT IN (SELECT id FROM print_jobs ORDER BY id DESC LIMIT ?)
`

func (q *Queries) PruneJobs(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneJobs, limit)
	return err
}

const setJobBytes = `-- name: SetJobBytes :execrows
UPDATE print_jobs SET bytes = ? WHERE id = ? AND state = 'pending'
`

type SetJobBytesParams struct {
	Bytes int64 `json:"bytes"`
	ID    int64 `json:"id"`
}

func (q *Queries) SetJobBytes(ctx context.Context, arg SetJobBytesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setJobBytes, arg.Bytes, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startJob = `-- name: StartJob :execrows
UPDATE print_jobs SET state = 'processing', started_at = ?, error = NULL WHERE id = ? AND state = 'pending'
`

type StartJobParams struct {
	StartedAt sql.NullInt64 `json:"started_at"`
	ID        int64         `json:"id"`
}

func (q *Queries) StartJob(ctx context.Context, arg StartJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startJob, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
