// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlitedb

import (
	"database/sql"
)

type BleDevice struct {
	ID         int64          `json:"id"`
	NativeID   string         `json:"native_id"`
	Name       string         `json:"name"`
	Address    string         `json:"address"`
	WriteUuid  string         `json:"write_uuid"`
	NotifyUuid sql.NullString `json:"notify_uuid"`
	LastSeenAt int64          `json:"last_seen_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

type LabelProfile struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	WidthUm   int64  `json:"width_um"`
	HeightUm  int64  `json:"height_um"`
	GapUm     int64  `json:"gap_um"`
	PaperType int64  `json:"paper_type"`
	Darkness  int64  `json:"darkness"`
	Speed     int64  `json:"speed"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type PrintJob struct {
	ID             int64          `json:"id"`
	PrinterID      int64          `json:"printer_id"`
	Name           string         `json:"name"`
	UserName       string         `json:"user_name"`
	State          string         `json:"state"`
	DocumentFormat string         `json:"document_format"`
	Copies         int64          `json:"copies"`
	Bytes          int64          `json:"bytes"`
	Error          sql.NullString `json:"error"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	CompletedAt    sql.NullInt64  `json:"completed_at"`
}

type Printer struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	Uuid      string        `json:"uuid"`
	Driver    string        `json:"driver"`
	DeviceID  sql.NullInt64 `json:"device_id"`
	ProfileID int64         `json:"profile_id"`
	Enabled   int64         `json:"enabled"`
	Advertise int64         `json:"advertise"`
	Airprint  int64         `json:"airprint"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}
