// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: printers.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createPrinter = `-- name: CreatePrinter :one
INSERT INTO printers (
    name, slug, uuid, driver, device_id, profile_id, enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, slug, uuid, driver, device_id, profile_id, enabled, created_at, updated_at
`

type CreatePrinterParams struct {
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	Uuid      string        `json:"uuid"`
	Driver    string        `json:"driver"`
	DeviceID  sql.NullInt64 `json:"device_id"`
	ProfileID int64         `json:"profile_id"`
	Enabled   int64         `json:"enabled"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}

func (q *Queries) CreatePrinter(ctx context.Context, arg CreatePrinterParams) (*Printer, error) {
	row := q.db.QueryRowContext(ctx, createPrinter,
		arg.Name,
		arg.Slug,
		arg.Uuid,
		arg.Driver,
		arg.DeviceID,
		arg.ProfileID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Printer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Uuid,
		&i.Driver,
		&i.DeviceID,
		&i.ProfileID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePrinter = `-- name: DeletePrinter :execrows
DELETE FROM printers WHERE id = ?
`

func (q *Queries) DeletePrinter(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrinter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPrinter = `-- name: GetPrinter :one
SELECT id, name, slug, uuid, driver, device_id, profile_id, enabled, created_at, updated_at FROM printers WHERE id = ?
`

func (q *Queries) GetPrinter(ctx context.Context, id int64) (*Printer, error) {
	row := q.db.QueryRowContext(ctx, getPrinter, id)
	var i Printer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Uuid,
		&i.Driver,
		&i.DeviceID,
		&i.ProfileID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPrinterBySlug = `-- name: GetPrinterBySlug :one
SELECT id, name, slug, uuid, driver, device_id, profile_id, enabled, created_at, updated_at FROM printers WHERE slug = ?
`

func (q *Queries) GetPrinterBySlug(ctx context.Context, slug string) (*Printer, error) {
	row := q.db.QueryRowContext(ctx, getPrinterBySlug, slug)
	var i Printer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Uuid,
		&i.Driver,
		&i.DeviceID,
		&i.ProfileID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPrinters = `-- name: ListPrinters :many
SELECT id, name, slug, uuid, driver, device_id, profile_id, enabled, created_at, updated_at FROM printers ORDER BY name ASC, id ASC
`

func (q *Queries) ListPrinters(ctx context.Context) ([]*Printer, error) {
	rows, err := q.db.QueryContext(ctx, listPrinters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Printer{}
	for rows.Next() {
		var i Printer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Uuid,
			&i.Driver,
			&i.DeviceID,
			&i.ProfileID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrinter = `-- name: UpdatePrinter :one
UPDATE printers
SET name = ?, driver = ?, device_id = ?, profile_id = ?, enabled = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, slug, uuid, driver, device_id, profile_id, enabled, created_at, updated_at
`

type UpdatePrinterParams struct {
	Name      string        `json:"name"`
	Driver    string        `json:"driver"`
	DeviceID  sql.NullInt64 `json:"device_id"`
	ProfileID int64         `json:"profile_id"`
	Enabled   int64         `json:"enabled"`
	UpdatedAt int64         `json:"updated_at"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdatePrinter(ctx context.Context, arg UpdatePrinterParams) (*Printer, error) {
	row := q.db.QueryRowContext(ctx, updatePrinter,
		arg.Name,
		arg.Driver,
		arg.DeviceID,
		arg.ProfileID,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Printer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Uuid,
		&i.Driver,
		&i.DeviceID,
		&i.ProfileID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
