// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: profiles.sql

package sqlitedb

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO label_profiles (
    name, width_um, height_um, gap_um, halftone_method, brightness, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, width_um, height_um, gap_um, created_at, updated_at, halftone_method, brightness
`

type CreateProfileParams struct {
	Name           string `json:"name"`
	WidthUm        int64  `json:"width_um"`
	HeightUm       int64  `json:"height_um"`
	GapUm          int64  `json:"gap_um"`
	HalftoneMethod int64  `json:"halftone_method"`
	Brightness     int64  `json:"brightness"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (*LabelProfile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.Name,
		arg.WidthUm,
		arg.HeightUm,
		arg.GapUm,
		arg.HalftoneMethod,
		arg.Brightness,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LabelProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WidthUm,
		&i.HeightUm,
		&i.GapUm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HalftoneMethod,
		&i.Brightness,
	)
	return &i, err
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM label_profiles WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, width_um, height_um, gap_um, created_at, updated_at, halftone_method, brightness FROM label_profiles WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id int64) (*LabelProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i LabelProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WidthUm,
		&i.HeightUm,
		&i.GapUm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HalftoneMethod,
		&i.Brightness,
	)
	return &i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, width_um, height_um, gap_um, created_at, updated_at, halftone_method, brightness FROM label_profiles ORDER BY name ASC, id ASC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]*LabelProfile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LabelProfile{}
	for rows.Next() {
		var i LabelProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WidthUm,
			&i.HeightUm,
			&i.GapUm,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HalftoneMethod,
			&i.Brightness,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE label_profiles
SET name = ?, width_um = ?, height_um = ?, gap_um = ?, halftone_method = ?, brightness = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, width_um, height_um, gap_um, created_at, updated_at, halftone_method, brightness
`

type UpdateProfileParams struct {
	Name           string `json:"name"`
	WidthUm        int64  `json:"width_um"`
	HeightUm       int64  `json:"height_um"`
	GapUm          int64  `json:"gap_um"`
	HalftoneMethod int64  `json:"halftone_method"`
	Brightness     int64  `json:"brightness"`
	UpdatedAt      int64  `json:"updated_at"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (*LabelProfile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.Name,
		arg.WidthUm,
		arg.HeightUm,
		arg.GapUm,
		arg.HalftoneMethod,
		arg.Brightness,
		arg.UpdatedAt,
		arg.ID,
	)
	var i LabelProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WidthUm,
		&i.HeightUm,
		&i.GapUm,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HalftoneMethod,
		&i.Brightness,
	)
	return &i, err
}
